### ISSUE TITLE
records qc

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/pubman#7]
Looks like there are only a few records that don't seem right. 

YEAR | TITLE
2103     Reforming disease classification system-are we there yet? Ann Transl Med
1000 | Construction and accessibility of a cross-species phenotype ontology along with gene annotations for biomedical research
1000 | Resources, challenges and way forward in rare mitochondrial diseases research

I recommend adding some qc before submitting into the file. Let me know if you can address before we release @pnrobinson

**Comment by pnrobinson** [comment]
Thanks, this is a parse issue -- I will see if I can fix this shortly.

**Comment by pnrobinson** [comment]
@iimpulse -- when are we planning on releasing?

**Comment by pnrobinson** [comment]
this is now fixed
